version: "3.7"

services:
  rails-db:
    image: postgres:12
    container_name: rails-db
    ports:
      - '5432:5432'
    expose:
      - 5432
    environment:
      POSTGRES_DB: rails-app
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
    volumes:
      - db:/var/lib/postgresql/data
  web:
    container_name: web
    build:
      context: ./rails-app
      dockerfile: Dockerfile
    ports:
      - 3010:3010
    working_dir: /rails-app
    volumes:
      - ./rails-app:/rails-app
      - bundle:/usr/local/bundle
      - node_modules:/rails-app/node_modules
      - tmp:/rails-app/tmp
      - log:/rails-app/log
    environment:
      DB_HOST: rails-db
      DB_NAME: rails-app
      DB_USER: postgresql
      DB_PASSWORD: postgresql
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3010 -b '0.0.0.0'"
    depends_on:
      - rails-db

volumes:
  db:
    driver: local
  bundle:
  node_modules:
  log:
  tmp:

