version: "3.7"

services:
  rails-db:
    image: postgres:12
    container_name: rails-db
    ports:
      - '5432:5432'
    expose:
      - 5432
    environment:
      POSTGRES_DB: rails-app
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
    volumes:
      - db:/var/lib/postgresql/data
  web:
    container_name: web
    build:
      context: ./rails-app
      dockerfile: Dockerfile
    ports:
      - 3010:3010
    working_dir: /rails-app
    volumes:
      - ./rails-app:/rails-app
      - bundle:/usr/local/bundle
      - node_modules:/rails-app/node_modules
      - tmp:/rails-app/tmp
      - log:/rails-app/log
    environment:
      DB_HOST: rails-db
      DB_NAME: rails-app
      DB_USER: postgresql
      DB_PASSWORD: postgresql
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3010 -b '0.0.0.0'"
    depends_on:
      - rails-db

  wordpress-db:
    platform: linux/x86_64 # NOTE(okubo): M!だとこの部分必要みたい
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - wordpress-db
    image: wordpress:latest
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  reverse-proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  hoge:
    image: nginx
    container_name: hoge
    volumes:
      - ./hoge:/usr/share/nginx/html
    ports:
      - 7001:80

volumes:
  db:
    driver: local
  db_data:
  bundle:
  node_modules:
  log:
  tmp:

